# Generated by Django 4.2.2 on 2023-06-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cards_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
